image: mcr.microsoft.com/dotnet/core/sdk:2.2

stages:
  - build
  - test

before_script:
  - dotnet restore

build debug:
  stage: build
  script:
    - dotnet build /t:Clean,Rebuild dmx-lib.sln /p:Configuration="Debug"

build release:
  stage: build
  script:
    - dotnet build /t:Clean,Rebuild dmx-lib.sln /p:Configuration="Release"
  
test:
  stage: test
  script:
    - dotnet test
