image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
  - build
  - test

before_script:
  - dotnet restore

build debug:
  stage: build
  script:
    - dotnet build /t:Clean,Rebuild dmx-lib.sln /p:Configuration="Debug"
  artifacts:
    paths:
      - DmxLib/bin/Debug/netstandard2.0/
      - DmxLib.Testing/bin/Debug/netcoreapp3.0/

build release:
  stage: build
  script:
    - dotnet build /t:Clean,Rebuild dmx-lib.sln /p:Configuration="Release"
  artifacts:
    paths:
      - DmxLib/bin/Release/netstandard2.0/
      - DmxLib.Testing/bin/Release/netcoreapp3.0/
  
test:
  stage: test
  script:
    - dotnet test
