image: mcr.microsoft.com/dotnet/core/sdk:2.2

stages:
  - build
  - test

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build
  
test:
  stage: test
  script:
    - dotnet test
