name: Push to GitHub Packages

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@v0.4
      id: nbgv
    - name: Build
      run: dotnet build -c Release /p:ContinuousIntegrationBuild=true
    - name: Pack
      run: dotnet pack -c Release --no-build /p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test -c Release --no-restore --no-build /p:ContinuousIntegrationBuild=true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DmxLib-nupkg-${{ steps.nbgv.outputs.Version }}
        path: |
          bin/Packages/Release/**/*
    - name: Add GitHub Packages NuGet Feed
      run: dotnet nuget add source --username akademischerverein --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/akademischerverein/index.json"
    - name: Push to GitHub Packages
      run: dotnet nuget push "bin/Packages/Release/**/*" --source "github"
