name: Push to GitHub Packages

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: DmxLib-nupkg-*
        merge-multiple: true
        path: artifacts
    - name: Add GitHub Packages NuGet Feed
      run: dotnet nuget add source --username akademischerverein --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/akademischerverein/index.json"
    - name: Push to GitHub Packages
      run: dotnet nuget push "artifacts/**/*" --source "github"
