name: Push to MyGet

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v5
      with:
        pattern: DmxLib-nupkg-*
        merge-multiple: true
        path: artifacts
    - name: Push to MyGet
      run: dotnet nuget push "artifacts/**/*" --source "https://www.myget.org/F/akademischerverein/api/v2/package" --api-key ${{ secrets.MYGET_TOKEN }}
